# flake8: noqa: B950
# fmt: off
# This file was generated by AutoHeuristic. Do not modify it manually!
# To regenerate this file, take a look at the steps in the README.md file inside torchgen/_autoheuristic/mm/
from typing import Optional

from torch._inductor.autoheuristic.autoheuristic_utils import (
    AHContext,
    AHMetadata,
    Choice,
)
from torch._inductor.autoheuristic.learnedheuristic_interface import (
    LearnedHeuristicDecision,
)


class GPURankingNew(LearnedHeuristicDecision):

    def __init__(self) -> None:
        self.choices: list[Choice] = []
        self.fill_choices()

    def check_precondition(self, metadata: AHMetadata, context: AHContext,) -> bool:
        return (
            metadata.name == self.get_name()
            and metadata.shared_memory == 101376
            and str(metadata.device_capa) == "(8, 6)"
        )

    def get_confidence_threshold(self) -> float:
        return 0.0

    def get_choice(self, idx: int) -> Optional[str]:
        if idx < len(self.choices):
            return self.choices[idx]
        return None

    def fill_choices(self) -> None:
        self.choices.append('extern_mm')
        self.choices.append('type=triton_BLOCK-M=16_BLOCK-K=16_BLOCK-N=16_numstages=1_numwarps=1')
        self.choices.append('type=triton_BLOCK-M=16_BLOCK-K=16_BLOCK-N=32_numstages=1_numwarps=2')
        self.choices.append('type=triton_BLOCK-M=16_BLOCK-K=32_BLOCK-N=16_numstages=1_numwarps=1')

    def get_name(self) -> str:
        return 'mm'

    def get_best_choices(self, context: AHContext) -> Optional[list[tuple[float, int]]]:
        if context.get_value('m*k') <= 1722240.0:
            return [(1.000, 2)]
        else:
            if context.get_value('m*n') <= 11960320.0:
                if str(context.get_value('mat1_dtype')) != 'torch.float16':
                    return [(1.000, 1)]
                else:
                    return [(0.333, 0), (0.333, 1), (0.333, 3)]
            else:
                if context.get_value('k*n') <= 16269312.0:
                    if str(context.get_value('mat1_dtype')) != 'torch.float16':
                        return [(0.667, 0), (0.333, 1)]
                    else:
                        return [(1.000, 0)]
                else:
                    return [(1.000, 0)]
